
import java.util.ArrayList;
import java.util.HashSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class TelaConsulta extends javax.swing.JFrame {
    
   
    /**
     * Creates new form TelaConsulta
     */
    public TelaConsulta() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        consultaPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        nomePacienteLbl = new javax.swing.JLabel();
        telefoneLabel = new javax.swing.JLabel();
        cpfLbl = new javax.swing.JLabel();
        dataConsultaLbl = new javax.swing.JLabel();
        jaPacienteCheckBox = new javax.swing.JCheckBox();
        cadastrarBtn = new javax.swing.JButton();
        nomePacienteTxt = new javax.swing.JTextField();
        telefoneTxt = new javax.swing.JTextField();
        cpfTxt = new javax.swing.JTextField();
        dataConsultaTxt = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Cadastrar Consulta");

        nomePacienteLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nomePacienteLbl.setText("Nome do(a) Paciente:");

        telefoneLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        telefoneLabel.setText("Telefone:");

        cpfLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cpfLbl.setText("CPF:");

        dataConsultaLbl.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        dataConsultaLbl.setText("Data da Consulta:");

        jaPacienteCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jaPacienteCheckBox.setText("Já é paciente");
        jaPacienteCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jaPacienteCheckBoxActionPerformed(evt);
            }
        });

        cadastrarBtn.setText("Cadastrar");
        cadastrarBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout consultaPanelLayout = new javax.swing.GroupLayout(consultaPanel);
        consultaPanel.setLayout(consultaPanelLayout);
        consultaPanelLayout.setHorizontalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jaPacienteCheckBox)
                    .addComponent(jLabel1)
                    .addGroup(consultaPanelLayout.createSequentialGroup()
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(cadastrarBtn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomePacienteLbl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                            .addComponent(telefoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpfLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dataConsultaLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nomePacienteTxt)
                            .addComponent(cpfTxt)
                            .addComponent(telefoneTxt)
                            .addComponent(dataConsultaTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE))))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        consultaPanelLayout.setVerticalGroup(
            consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(consultaPanelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(46, 46, 46)
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nomePacienteLbl)
                    .addComponent(nomePacienteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoneLabel)
                    .addComponent(telefoneTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLbl)
                    .addComponent(cpfTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(consultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dataConsultaLbl)
                    .addComponent(dataConsultaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jaPacienteCheckBox)
                .addGap(18, 18, 18)
                .addComponent(cadastrarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(consultaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jaPacienteCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jaPacienteCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jaPacienteCheckBoxActionPerformed

    private void cadastrarBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarBtnActionPerformed
        if(!emptyFields() && regex()){
            ListaConsulta.adicionar(getConsulta());
            Agendamento.atualizar();
            nomePacienteTxt.setText("");
            telefoneTxt.setText("");
            cpfTxt.setText("");
            dataConsultaTxt.setText("");
            dataConsultaTxt.setText("");
            jaPacienteCheckBox.setSelected(false);
        }
    }//GEN-LAST:event_cadastrarBtnActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrarBtn;
    private javax.swing.JPanel consultaPanel;
    private javax.swing.JLabel cpfLbl;
    private javax.swing.JTextField cpfTxt;
    private javax.swing.JLabel dataConsultaLbl;
    private javax.swing.JTextField dataConsultaTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox jaPacienteCheckBox;
    private javax.swing.JLabel nomePacienteLbl;
    private javax.swing.JTextField nomePacienteTxt;
    private javax.swing.JLabel telefoneLabel;
    private javax.swing.JTextField telefoneTxt;
    // End of variables declaration//GEN-END:variables

private boolean emptyFields(){
    boolean empty = true;
    
    if(nomePacienteTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Campo paciente não pode ficar vazio");
    }else if(telefoneTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Campo telefone não pode ficar vazio");
    }else if(cpfTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(rootPane,"Campo cpf não pode ficar vazio");
    }else if(dataConsultaTxt.getText().trim().isEmpty()){
        JOptionPane.showMessageDialog(rootPane, "Campo data não pode ficar vazio");
    }else{
        empty = false;
    }
    return empty;
}

private boolean regex(){
    boolean valido = false;
    
    if(!telefoneTxt.getText().matches("^\\([1-9]{2}\\) (?:[2-8]|9[1-9])[0-9]{3}\\-[0-9]{4}$")){
        JOptionPane.showMessageDialog(rootPane,"Telefone precisa ser no formato: (xx) xxxxx-xxxx");
    }else if(!dataConsultaTxt.getText().trim().matches("[0-9]{2}[/][0-9]{2}[/][0-9]{4}")){
        JOptionPane.showMessageDialog(rootPane,"Data precisa ser no formato: DD/MM/AAAA");
    }else if(!cpfTxt.getText().trim().matches("[0-9]{3}[.][0-9]{3}[.][0-9]{3}[-][0-9]{2}")){
        JOptionPane.showMessageDialog(rootPane,"CPF precisa ser no formato: 111.222.333-44");
    }else{
        valido = true;
    }
    return valido;
}



private Consulta getConsulta(){
    Consulta consulta = new Consulta();
    consulta.setPaciente(nomePacienteTxt.getText().trim().toUpperCase());
    consulta.setCpf(cpfTxt.getText().trim());
    consulta.setTelefone(telefoneTxt.getText());
    consulta.setData(dataConsultaTxt.getText().trim());
    if(jaPacienteCheckBox.isSelected()){
        consulta.setJaEraPaciente("Sim");
    }else{
        consulta.setJaEraPaciente("Não");
        
    }
    consulta.setConsultaRealizada("Não");
    return consulta;
}

}
