/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Usuario
 */
public class TelaFinalizarConsulta extends javax.swing.JFrame {

    /**
     * Creates new form TelaFinalizarConsulta
     */
    public TelaFinalizarConsulta() {
        initComponents();
         setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        finalizarConsultaPanel = new javax.swing.JPanel();
        detalhesLbl = new javax.swing.JLabel();
        ConsultaRealizadaCheckBox = new javax.swing.JCheckBox();
        receitaLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        obsTextArea = new javax.swing.JTextArea();
        finalizarBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        detalhesLbl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        detalhesLbl.setText("Detalhes da Consulta");

        ConsultaRealizadaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        ConsultaRealizadaCheckBox.setText("Consulta Realizada");

        receitaLbl.setText("Receita e observações:");

        obsTextArea.setColumns(20);
        obsTextArea.setRows(5);
        jScrollPane1.setViewportView(obsTextArea);

        finalizarBtn.setText("Finalizar");

        javax.swing.GroupLayout finalizarConsultaPanelLayout = new javax.swing.GroupLayout(finalizarConsultaPanel);
        finalizarConsultaPanel.setLayout(finalizarConsultaPanelLayout);
        finalizarConsultaPanelLayout.setHorizontalGroup(
            finalizarConsultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalizarConsultaPanelLayout.createSequentialGroup()
                .addGroup(finalizarConsultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(finalizarConsultaPanelLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(finalizarConsultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(receitaLbl)
                            .addComponent(ConsultaRealizadaCheckBox)
                            .addComponent(detalhesLbl)))
                    .addGroup(finalizarConsultaPanelLayout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(finalizarBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        finalizarConsultaPanelLayout.setVerticalGroup(
            finalizarConsultaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(finalizarConsultaPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(detalhesLbl)
                .addGap(29, 29, 29)
                .addComponent(ConsultaRealizadaCheckBox)
                .addGap(18, 18, 18)
                .addComponent(receitaLbl)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(finalizarBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalizarConsultaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(finalizarConsultaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFinalizarConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFinalizarConsulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ConsultaRealizadaCheckBox;
    private javax.swing.JLabel detalhesLbl;
    private javax.swing.JButton finalizarBtn;
    private javax.swing.JPanel finalizarConsultaPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea obsTextArea;
    private javax.swing.JLabel receitaLbl;
    // End of variables declaration//GEN-END:variables
}
